### ISSUE TITLE
New Color?

### ISSUE THREAD

**Issue by PlavnikHacks** [HackerHansen/1v1.lol-aimbot#12]
I've tried getting the new color but the head is multiple colors, I turned down sensitivity but then it just shoots at sky and stuff.

Code outdated or patched by chance?

**Comment by HackerHansen** [comment]
Turn up the color variance, and try grabbing the color from a screenshot instead of a video if you can. 

Color aimbots can't really be "patched" (it literally just searches for colors). However, they aren't really that great in the first place so don't expect too much out of it lol
