### ISSUE TITLE
Hackers

### ISSUE THREAD

**Issue by HACKER-CREA** [HackerHansen/1v1.lol-aimbot#16]
The hackers are always winning so I wanna win to

**Comment by HACKER-CREA** [comment]
Y they hackers always winnin

**Comment by HACKER-CREA** [comment]
I wanna hack

**Comment by HACKER-CREA** [comment]
I wanna be like faze jarvis

**Comment by HackerHansen** [comment]
Go to my 1v1.yeet repository if you're here to download hacks and not learn scripting lol
